# Generated by Django 5.0.6 on 2024-05-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desc',
            field=models.TextField(default=1, verbose_name='работа'),
            preserve_default=False,
        ),
    ]
